[env:esp32-c3-devkitm-1]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino

; Serial Monitor & Upload Settings
monitor_speed = 115200
upload_speed = 921600
upload_port = COM3
monitor_port = COM3

; Build Flags
build_flags =
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D ARDUINO_USB_MODE=1

; Libraries from PlatformIO registry
lib_deps =
    adafruit/Adafruit GFX Library@^1.11.9
    adafruit/Adafruit ST7735 and ST7789 Library@^1.10.3
