#ifndef SPRITES_H
#define SPRITES_H

#include <Arduino.h>

// Colors in RGB565 format
#define C_TRANS 0x0000 // Transparent (Black)
#define C_RED   0xF800
#define C_BLUE  0x001F
#define C_SKIN  0xFD68
#define C_BRWN  0x8200
#define C_YELW  0xFFE0
#define C_GREN  0x07E0
#define C_BLK   0x0001 // Not strictly black to distinguish from transparent

// 16x16 Mario Sprite
const uint16_t marioSprite[256] PROGMEM = {
    C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_RED,  C_RED,  C_RED,  C_RED,  C_RED,  C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,
    C_TRANS,C_TRANS,C_TRANS,C_RED,  C_RED,  C_RED,  C_RED,  C_RED,  C_RED,  C_RED,  C_RED,  C_RED,  C_TRANS,C_TRANS,C_TRANS,C_TRANS,
    C_TRANS,C_TRANS,C_TRANS,C_BRWN, C_BRWN, C_BRWN, C_SKIN, C_SKIN, C_BRWN, C_SKIN, C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,
    C_TRANS,C_TRANS,C_BRWN, C_SKIN, C_BRWN, C_SKIN, C_SKIN, C_SKIN, C_BRWN, C_SKIN, C_SKIN, C_SKIN, C_TRANS,C_TRANS,C_TRANS,C_TRANS,
    C_TRANS,C_TRANS,C_BRWN, C_SKIN, C_BRWN, C_BRWN, C_SKIN, C_SKIN, C_SKIN, C_BRWN, C_SKIN, C_SKIN, C_SKIN, C_TRANS,C_TRANS,C_TRANS,
    C_TRANS,C_TRANS,C_BRWN, C_BRWN, C_SKIN, C_SKIN, C_SKIN, C_SKIN, C_BRWN, C_BRWN, C_BRWN, C_BRWN, C_TRANS,C_TRANS,C_TRANS,C_TRANS,
    C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_SKIN, C_SKIN, C_SKIN, C_SKIN, C_SKIN, C_SKIN, C_SKIN, C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,
    C_TRANS,C_TRANS,C_BRWN, C_BRWN, C_RED,  C_RED,  C_BLUE, C_RED,  C_RED,  C_RED,  C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,
    C_TRANS,C_BRWN, C_BRWN, C_BRWN, C_RED,  C_RED,  C_BLUE, C_RED,  C_RED,  C_RED,  C_BRWN, C_BRWN, C_BRWN, C_TRANS,C_TRANS,C_TRANS,
    C_BRWN, C_BRWN, C_BRWN, C_BRWN, C_RED,  C_RED,  C_BLUE, C_BLUE, C_BLUE, C_RED,  C_BRWN, C_BRWN, C_BRWN, C_BRWN, C_TRANS,C_TRANS,
    C_SKIN, C_SKIN, C_BRWN, C_RED,  C_BLUE, C_YELW, C_BLUE, C_BLUE, C_YELW, C_BLUE, C_RED,  C_BRWN, C_SKIN, C_SKIN, C_TRANS,C_TRANS,
    C_SKIN, C_SKIN, C_SKIN, C_BLUE, C_BLUE, C_BLUE, C_BLUE, C_BLUE, C_BLUE, C_BLUE, C_BLUE, C_SKIN, C_SKIN, C_SKIN, C_TRANS,C_TRANS,
    C_SKIN, C_SKIN, C_BLUE, C_BLUE, C_BLUE, C_BLUE, C_BLUE, C_BLUE, C_BLUE, C_BLUE, C_BLUE, C_BLUE, C_SKIN, C_SKIN, C_TRANS,C_TRANS,
    C_TRANS,C_TRANS,C_BLUE, C_BLUE, C_BLUE, C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_BLUE, C_BLUE, C_BLUE, C_TRANS,C_TRANS,C_TRANS,C_TRANS,
    C_TRANS,C_BRWN, C_BRWN, C_BRWN, C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_BRWN, C_BRWN, C_BRWN, C_TRANS,C_TRANS,C_TRANS,
    C_BRWN, C_BRWN, C_BRWN, C_BRWN, C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_BRWN, C_BRWN, C_BRWN, C_BRWN, C_TRANS,C_TRANS
};

// 16x16 Pipe Top
const uint16_t pipeTopSprite[256] PROGMEM = {
    C_BLK,  C_BLK,  C_BLK,  C_BLK,  C_BLK,  C_BLK,  C_BLK,  C_BLK,  C_BLK,  C_BLK,  C_BLK,  C_BLK,  C_BLK,  C_BLK,  C_BLK,  C_BLK,
    C_BLK,  C_GREN, C_GREN, C_GREN, C_GREN, C_GREN, C_GREN, C_GREN, C_GREN, C_GREN, C_GREN, C_GREN, C_GREN, C_GREN, C_GREN, C_BLK,
    C_BLK,  C_GREN, C_GREN, C_GREN, C_GREN, C_GREN, C_GREN, C_GREN, C_GREN, C_GREN, C_GREN, C_GREN, C_GREN, C_GREN, C_GREN, C_BLK,
    C_BLK,  C_GREN, C_GREN, C_GREN, C_GREN, C_GREN, C_GREN, C_GREN, C_GREN, C_GREN, C_GREN, C_GREN, C_GREN, C_GREN, C_GREN, C_BLK,
    C_BLK,  C_GREN, C_GREN, C_GREN, C_GREN, C_GREN, C_GREN, C_GREN, C_GREN, C_GREN, C_GREN, C_GREN, C_GREN, C_GREN, C_GREN, C_BLK,
    C_BLK,  C_GREN, C_GREN, C_GREN, C_GREN, C_GREN, C_GREN, C_GREN, C_GREN, C_GREN, C_GREN, C_GREN, C_GREN, C_GREN, C_GREN, C_BLK,
    C_BLK,  C_BLK,  C_BLK,  C_BLK,  C_BLK,  C_BLK,  C_BLK,  C_BLK,  C_BLK,  C_BLK,  C_BLK,  C_BLK,  C_BLK,  C_BLK,  C_BLK,  C_BLK,
    C_TRANS,C_TRANS,C_BLK,  C_GREN, C_GREN, C_GREN, C_GREN, C_GREN, C_GREN, C_GREN, C_GREN, C_GREN, C_GREN, C_BLK,  C_TRANS,C_TRANS,
    C_TRANS,C_TRANS,C_BLK,  C_GREN, C_GREN, C_GREN, C_GREN, C_GREN, C_GREN, C_GREN, C_GREN, C_GREN, C_GREN, C_BLK,  C_TRANS,C_TRANS,
    C_TRANS,C_TRANS,C_BLK,  C_GREN, C_GREN, C_GREN, C_GREN, C_GREN, C_GREN, C_GREN, C_GREN, C_GREN, C_GREN, C_BLK,  C_TRANS,C_TRANS,
    C_TRANS,C_TRANS,C_BLK,  C_GREN, C_GREN, C_GREN, C_GREN, C_GREN, C_GREN, C_GREN, C_GREN, C_GREN, C_GREN, C_BLK,  C_TRANS,C_TRANS,
    C_TRANS,C_TRANS,C_BLK,  C_GREN, C_GREN, C_GREN, C_GREN, C_GREN, C_GREN, C_GREN, C_GREN, C_GREN, C_GREN, C_BLK,  C_TRANS,C_TRANS,
    C_TRANS,C_TRANS,C_BLK,  C_GREN, C_GREN, C_GREN, C_GREN, C_GREN, C_GREN, C_GREN, C_GREN, C_GREN, C_GREN, C_BLK,  C_TRANS,C_TRANS,
    C_TRANS,C_TRANS,C_BLK,  C_GREN, C_GREN, C_GREN, C_GREN, C_GREN, C_GREN, C_GREN, C_GREN, C_GREN, C_GREN, C_BLK,  C_TRANS,C_TRANS,
    C_TRANS,C_TRANS,C_BLK,  C_GREN, C_GREN, C_GREN, C_GREN, C_GREN, C_GREN, C_GREN, C_GREN, C_GREN, C_GREN, C_BLK,  C_TRANS,C_TRANS,
    C_TRANS,C_TRANS,C_BLK,  C_GREN, C_GREN, C_GREN, C_GREN, C_GREN, C_GREN, C_GREN, C_GREN, C_GREN, C_GREN, C_BLK,  C_TRANS,C_TRANS
};

// 16x16 Brick Sprite (Classic SMB floor block)
const uint16_t brickSprite[256] PROGMEM = {
    C_BLK,  C_BLK,  C_BLK,  C_BLK,  C_BLK,  C_BLK,  C_BLK,  C_BLK,  C_BLK,  C_BLK,  C_BLK,  C_BLK,  C_BLK,  C_BLK,  C_BLK,  C_BLK,
    C_BLK,  C_YELW, C_YELW, C_YELW, C_YELW, C_YELW, C_YELW, C_YELW, C_BLK,  C_YELW, C_YELW, C_YELW, C_YELW, C_YELW, C_YELW, C_BLK,
    C_BLK,  C_YELW, C_BRWN, C_BRWN, C_BRWN, C_BRWN, C_BRWN, C_BRWN, C_BLK,  C_YELW, C_BRWN, C_BRWN, C_BRWN, C_BRWN, C_BRWN, C_BLK,
    C_BLK,  C_YELW, C_BRWN, C_BRWN, C_BRWN, C_BRWN, C_BRWN, C_BRWN, C_BLK,  C_YELW, C_BRWN, C_BRWN, C_BRWN, C_BRWN, C_BRWN, C_BLK,
    C_BLK,  C_BLK,  C_BLK,  C_BLK,  C_BLK,  C_BLK,  C_BLK,  C_BLK,  C_BLK,  C_BLK,  C_BLK,  C_BLK,  C_BLK,  C_BLK,  C_BLK,  C_BLK,
    C_YELW, C_YELW, C_YELW, C_BLK,  C_YELW, C_YELW, C_YELW, C_YELW, C_YELW, C_YELW, C_YELW, C_BLK,  C_YELW, C_YELW, C_YELW, C_YELW,
    C_YELW, C_BRWN, C_BRWN, C_BLK,  C_YELW, C_BRWN, C_BRWN, C_BRWN, C_BRWN, C_BRWN, C_BRWN, C_BLK,  C_YELW, C_BRWN, C_BRWN, C_BRWN,
    C_YELW, C_BRWN, C_BRWN, C_BLK,  C_YELW, C_BRWN, C_BRWN, C_BRWN, C_BRWN, C_BRWN, C_BRWN, C_BLK,  C_YELW, C_BRWN, C_BRWN, C_BRWN,
    C_BLK,  C_BLK,  C_BLK,  C_BLK,  C_BLK,  C_BLK,  C_BLK,  C_BLK,  C_BLK,  C_BLK,  C_BLK,  C_BLK,  C_BLK,  C_BLK,  C_BLK,  C_BLK,
    C_BLK,  C_YELW, C_YELW, C_YELW, C_YELW, C_YELW, C_YELW, C_YELW, C_BLK,  C_YELW, C_YELW, C_YELW, C_YELW, C_YELW, C_YELW, C_BLK,
    C_BLK,  C_YELW, C_BRWN, C_BRWN, C_BRWN, C_BRWN, C_BRWN, C_BRWN, C_BLK,  C_YELW, C_BRWN, C_BRWN, C_BRWN, C_BRWN, C_BRWN, C_BLK,
    C_BLK,  C_YELW, C_BRWN, C_BRWN, C_BRWN, C_BRWN, C_BRWN, C_BRWN, C_BLK,  C_YELW, C_BRWN, C_BRWN, C_BRWN, C_BRWN, C_BRWN, C_BLK,
    C_BLK,  C_BLK,  C_BLK,  C_BLK,  C_BLK,  C_BLK,  C_BLK,  C_BLK,  C_BLK,  C_BLK,  C_BLK,  C_BLK,  C_BLK,  C_BLK,  C_BLK,  C_BLK,
    C_YELW, C_YELW, C_YELW, C_BLK,  C_YELW, C_YELW, C_YELW, C_YELW, C_YELW, C_YELW, C_YELW, C_BLK,  C_YELW, C_YELW, C_YELW, C_YELW,
    C_YELW, C_BRWN, C_BRWN, C_BLK,  C_YELW, C_BRWN, C_BRWN, C_BRWN, C_BRWN, C_BRWN, C_BRWN, C_BLK,  C_YELW, C_BRWN, C_BRWN, C_BRWN,
    C_YELW, C_BRWN, C_BRWN, C_BLK,  C_YELW, C_BRWN, C_BRWN, C_BRWN, C_BRWN, C_BRWN, C_BRWN, C_BLK,  C_YELW, C_BRWN, C_BRWN, C_BRWN
};

// 16x16 Small Cloud/Bush Tile (Can be tinted or drawn as white)
#define C_WHT   0xFFFF
#define C_SKY   0x5CDF // The background color
const uint16_t cloudSprite[256] PROGMEM = {
    C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_WHT,  C_WHT,  C_WHT,  C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,
    C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_WHT,  C_WHT,  C_WHT,  C_WHT,  C_WHT,  C_WHT,  C_WHT,  C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,
    C_TRANS,C_TRANS,C_TRANS,C_WHT,  C_WHT,  C_WHT,  C_WHT,  C_WHT,  C_WHT,  C_WHT,  C_WHT,  C_WHT,  C_TRANS,C_TRANS,C_TRANS,C_TRANS,
    C_TRANS,C_TRANS,C_WHT,  C_WHT,  C_WHT,  C_WHT,  C_WHT,  C_WHT,  C_WHT,  C_WHT,  C_WHT,  C_WHT,  C_WHT,  C_TRANS,C_TRANS,C_TRANS,
    C_TRANS,C_WHT,  C_WHT,  C_WHT,  C_WHT,  C_WHT,  C_WHT,  C_WHT,  C_WHT,  C_WHT,  C_WHT,  C_WHT,  C_WHT,  C_WHT,  C_TRANS,C_TRANS,
    C_WHT,  C_WHT,  C_WHT,  C_WHT,  C_WHT,  C_WHT,  C_WHT,  C_WHT,  C_WHT,  C_WHT,  C_WHT,  C_WHT,  C_WHT,  C_WHT,  C_WHT,  C_TRANS,
    C_WHT,  C_WHT,  C_WHT,  C_WHT,  C_WHT,  C_WHT,  C_WHT,  C_WHT,  C_WHT,  C_WHT,  C_WHT,  C_WHT,  C_WHT,  C_WHT,  C_WHT,  C_WHT,
    C_WHT,  C_WHT,  C_WHT,  C_WHT,  C_WHT,  C_WHT,  C_WHT,  C_WHT,  C_WHT,  C_WHT,  C_WHT,  C_WHT,  C_WHT,  C_WHT,  C_WHT,  C_WHT,
    C_WHT,  C_WHT,  C_WHT,  C_WHT,  C_WHT,  C_WHT,  C_WHT,  C_WHT,  C_WHT,  C_WHT,  C_WHT,  C_WHT,  C_WHT,  C_WHT,  C_WHT,  C_WHT,
    C_WHT,  C_WHT,  C_WHT,  C_WHT,  C_WHT,  C_WHT,  C_WHT,  C_WHT,  C_WHT,  C_WHT,  C_WHT,  C_WHT,  C_WHT,  C_WHT,  C_WHT,  C_WHT,
    C_WHT,  C_WHT,  C_WHT,  C_WHT,  C_WHT,  C_WHT,  C_WHT,  C_WHT,  C_WHT,  C_WHT,  C_WHT,  C_WHT,  C_WHT,  C_WHT,  C_WHT,  C_TRANS,
    C_TRANS,C_WHT,  C_WHT,  C_WHT,  C_WHT,  C_WHT,  C_WHT,  C_WHT,  C_WHT,  C_WHT,  C_WHT,  C_WHT,  C_WHT,  C_WHT,  C_TRANS,C_TRANS,
    C_TRANS,C_TRANS,C_WHT,  C_WHT,  C_WHT,  C_WHT,  C_WHT,  C_WHT,  C_WHT,  C_WHT,  C_WHT,  C_WHT,  C_WHT,  C_TRANS,C_TRANS,C_TRANS,
    C_TRANS,C_TRANS,C_TRANS,C_WHT,  C_WHT,  C_WHT,  C_WHT,  C_WHT,  C_WHT,  C_WHT,  C_WHT,  C_WHT,  C_TRANS,C_TRANS,C_TRANS,C_TRANS,
    C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_WHT,  C_WHT,  C_WHT,  C_WHT,  C_WHT,  C_WHT,  C_WHT,  C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,
    C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_WHT,  C_WHT,  C_WHT,  C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS
};

// 16x16 Goomba Sprite
const uint16_t goombaSprite[256] PROGMEM = {
    C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_BRWN, C_BRWN, C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,
    C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_BRWN, C_BRWN, C_BRWN, C_BRWN, C_BRWN, C_BRWN, C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,
    C_TRANS,C_TRANS,C_TRANS,C_BRWN, C_BRWN, C_BRWN, C_BRWN, C_BRWN, C_BRWN, C_BRWN, C_BRWN, C_BRWN, C_BRWN, C_TRANS,C_TRANS,C_TRANS,
    C_TRANS,C_TRANS,C_BRWN, C_BRWN, C_BRWN, C_BRWN, C_BRWN, C_BRWN, C_BRWN, C_BRWN, C_BRWN, C_BRWN, C_BRWN, C_BRWN, C_TRANS,C_TRANS,
    C_TRANS,C_BRWN, C_BRWN, C_BRWN, C_WHT,  C_WHT,  C_BRWN, C_BRWN, C_BRWN, C_BRWN, C_WHT,  C_WHT,  C_BRWN, C_BRWN, C_BRWN, C_TRANS,
    C_TRANS,C_BRWN, C_BRWN, C_WHT,  C_BLK,  C_WHT,  C_BRWN, C_BRWN, C_BRWN, C_BRWN, C_WHT,  C_BLK,  C_WHT,  C_BRWN, C_BRWN, C_TRANS,
    C_BRWN, C_BRWN, C_BRWN, C_WHT,  C_BLK,  C_WHT,  C_BRWN, C_BRWN, C_BRWN, C_BRWN, C_WHT,  C_BLK,  C_WHT,  C_BRWN, C_BRWN, C_BRWN,
    C_BRWN, C_BRWN, C_BRWN, C_BRWN, C_WHT,  C_WHT,  C_BRWN, C_BRWN, C_BRWN, C_BRWN, C_WHT,  C_WHT,  C_BRWN, C_BRWN, C_BRWN, C_BRWN,
    C_BRWN, C_BRWN, C_BRWN, C_BRWN, C_BRWN, C_BRWN, C_BLK,  C_BLK,  C_BLK,  C_BLK,  C_BRWN, C_BRWN, C_BRWN, C_BRWN, C_BRWN, C_BRWN,
    C_BRWN, C_BRWN, C_BRWN, C_BRWN, C_BRWN, C_BLK,  C_YELW, C_YELW, C_YELW, C_YELW, C_BLK,  C_BRWN, C_BRWN, C_BRWN, C_BRWN, C_BRWN,
    C_BRWN, C_BRWN, C_BRWN, C_BRWN, C_BRWN, C_BLK,  C_YELW, C_YELW, C_YELW, C_YELW, C_BLK,  C_BRWN, C_BRWN, C_BRWN, C_BRWN, C_BRWN,
    C_TRANS,C_BRWN, C_BRWN, C_BRWN, C_BRWN, C_BRWN, C_BLK,  C_YELW, C_YELW, C_BLK,  C_BRWN, C_BRWN, C_BRWN, C_BRWN, C_BRWN, C_TRANS,
    C_TRANS,C_TRANS,C_BRWN, C_BRWN, C_BRWN, C_BRWN, C_BRWN, C_BLK,  C_BLK,  C_BRWN, C_BRWN, C_BRWN, C_BRWN, C_BRWN, C_TRANS,C_TRANS,
    C_TRANS,C_TRANS,C_BLK,  C_BLK,  C_BLK,  C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_BLK,  C_BLK,  C_BLK,  C_TRANS,C_TRANS,
    C_TRANS,C_BLK,  C_BLK,  C_BLK,  C_BLK,  C_BLK,  C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_BLK,  C_BLK,  C_BLK,  C_BLK,  C_BLK,  C_TRANS,
    C_BLK,  C_BLK,  C_BLK,  C_BLK,  C_BLK,  C_BLK,  C_BLK,  C_TRANS,C_TRANS,C_BLK,  C_BLK,  C_BLK,  C_BLK,  C_BLK,  C_BLK,  C_BLK
};

#endif
